language: csharp
solution: TrueCraft.sln
mono:
    - latest
before_install:
    - git submodule update --init --recursive
install:
    - nuget restore TrueCraft.sln
    - nuget install NUnit.Runners -Version 3.2.1 -OutputDirectory testrunner
script:
    - xbuild TrueCraft.sln
    - |
        mono \
            ./testrunner/NUnit.ConsoleRunner.3.2.1/tools/nunit3-console.exe \
            ./TrueCraft.Core.Test/TrueCraft.Core.Test.csproj
